# Day 1:Introduction to ML

# Numpy Revision

In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [5]:
#Convert into array
list1 =np.array(my_list)
list1

array([1, 2, 3, 4])

In [7]:
my_list2=np.array(range(1,5))
my_list2

array([1, 2, 3, 4])

In [8]:
#1-D array
a= np.array([1,2,3])

In [10]:
#2-D array
b=np.array([[9,8,7],[6,5,4]])
b

array([[9, 8, 7],
       [6, 5, 4]])

In [11]:
#2-D array
b1=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b1

array([[9., 8., 7.],
       [6., 5., 4.]])

In [12]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
a1=np.array(matrix)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a1.ndim

2

In [19]:
a1.shape

(3, 3)

In [20]:
a.size

3

In [21]:
a.nbytes

12

In [22]:
np.array([[True, False],[True, False]])

array([[ True, False],
       [ True, False]])

In [23]:
x= np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [24]:
a.dtype

dtype('int32')

In [26]:
#Random number
np.random.rand(4,2)

array([[0.82257201, 0.22169234],
       [0.51204352, 0.09705192],
       [0.44245299, 0.9426424 ],
       [0.43520719, 0.35870687]])

In [27]:
np.random.randn(3)

array([ 0.30359368,  1.56402427, -1.67046453])

In [28]:
np.random.randint(2,100)

8

In [29]:
r1=np.random.randint(1,10,8)
r1

array([7, 9, 1, 8, 7, 4, 2, 5])

In [30]:
r1.max()

9

In [31]:
r1.min()

1

In [32]:
r1.argmax()

1

In [33]:
r1.argmin()

2

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [39]:
a+2

array([3, 4, 5])

In [40]:
a-2

array([-1,  0,  1])

In [41]:
a*2

array([2, 4, 6])

In [42]:
a/2

array([0.5, 1. , 1.5])

In [43]:
a+a

array([2, 4, 6])

In [44]:
a ** 3

array([ 1,  8, 27], dtype=int32)

In [45]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [46]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Pandas Revision

In [47]:
import pandas as pd


1.Series
2.DataFrame

In [49]:
obj = pd.Series([1,"John",3.5,"Hey"])
obj

0       1
1    John
2     3.5
3     Hey
dtype: object

In [50]:
obj[1]

'John'

In [51]:
obj1 = pd.Series([1,"John",3.5,"Hey"],index=["a","b","c","d"])
obj1

a       1
b    John
c     3.5
d     Hey
dtype: object

In [53]:
obj1["b"]

'John'

In [54]:
obj1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [55]:
score={"Jane":90, "Bill":80,"Elon":85,"Tom":75,"Tim":95}
names=pd.Series(score)
names

Jane    90
Bill    80
Elon    85
Tom     75
Tim     95
dtype: int64

In [56]:
names[names<80]

Tom    75
dtype: int64

In [57]:
names.isnull()

Jane    False
Bill    False
Elon    False
Tom     False
Tim     False
dtype: bool

In [59]:
import pandas as pd
df=pd.read_csv('nyc_weather.csv')
df

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [60]:
df['Temperature'].max()

50

In [61]:
#Calculate Event=Rain
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [63]:
#Calculate avergae Windspeed
df['WindSpeedMPH'].mean()

6.892857142857143