In [ ]:
import numpy as np

In [ ]:
m=np.array([[10,20,30,40],[23,34,45,55]])

In [ ]:
m.size

2

In [ ]:
print(m)

[list([5, 10, 20, 30, 40]) list([23, 34, 45, 55])]


In [ ]:
m.shape

(2,)

In [ ]:
m.ndim

1

In [ ]:
m=np.array([[10,20,30,40],[23,34,45,55]])

In [ ]:
m[0][2]

30

In [ ]:
m=np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333]])
print(m)

[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]]


In [ ]:
#slice [start:end:step]
m[0:2,0:2]
m[1:3,2:4]

array([[ 77,  88],
       [222, 333]])

In [ ]:
m=np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333]])
for i in m:
    print(i)

[11 22 33 44]
[55 66 77 88]
[ 99 111 222 333]


In [ ]:
len(m[0])

4

In [ ]:
m=np.array([[11,22,33,44],[55,66,77,88],[99,111,222,333]])
for sublist in m:
    for element in sublist:
        print(j)

11
22
33
44
55
66
77
88
99
111
222
333


In [ ]:
for i in np.nditer(m[::]):
    print(i)

11
22
33
44
55
66
77
88
99
111
222
333


In [ ]:
m=np.arange(1,13)
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
m.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m=np.arange(1,24,2).reshape(3,4)
print(m)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [ ]:
m=np.linspace(1,12,4)
print(m)

[ 1.          4.66666667  8.33333333 12.        ]


In [ ]:
from numpy import random

In [ ]:
print(random.randint(6))

4


In [ ]:
m1=np.arange(1,11).reshape(5,2)

In [ ]:
m2=np.arange(101,111).reshape(5,2)

In [ ]:
m2

array([[101, 102],
       [103, 104],
       [105, 106],
       [107, 108],
       [109, 110]])

In [ ]:
m1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
m3=m1*m2
print(m3)

[[ 101  204]
 [ 309  416]
 [ 525  636]
 [ 749  864]
 [ 981 1100]]


In [ ]:
m=random.randint(1,50,size=(5,5))

In [ ]:
m

array([[ 9, 36, 47, 26, 38],
       [27, 13, 15,  6,  8],
       [45,  8, 33,  9,  6],
       [47, 13, 14, 49, 43],
       [36,  1, 42, 17, 30]])

In [ ]:
v=np.where(m>=30)
print(v)#list of x,y indexes that satisfies condition
row=v[0]
column=v[1]
i=0
j=0
'''while i<len(row):
    print(m[row[i]][column[j]])
    i+=1
    j+=1'''
print(m[v])



(array([0, 0, 0, 2, 2, 3, 3, 3, 4, 4, 4]), array([1, 2, 4, 0, 2, 0, 3, 4, 0, 2, 4]))
[36 47 38 45 33 47 49 43 36 42 30]


In [ ]:
np.sort(m,axis=1)

array([[ 9, 26, 36, 38, 47],
       [ 6,  8, 13, 15, 27],
       [ 6,  8,  9, 33, 45],
       [13, 14, 43, 47, 49],
       [ 1, 17, 30, 36, 42]])

In [ ]:
print(random.randint(100,size=(6,6)))

[[79 60 62 95 62 13]
 [37 22 77 12 45 76]
 [74  8 33 30 61 13]
 [84 51 11 13 27 71]
 [96 24 27 95 78 20]
 [78 89 28 64 52 68]]


In [ ]:
random.choice(["aa","bb","cc","dd","ee","ff","gg","hh","ii","jj"],size=(5,6))

array([['bb', 'ff', 'aa', 'bb', 'ee', 'jj'],
       ['ee', 'ff', 'gg', 'ee', 'bb', 'bb'],
       ['aa', 'ii', 'jj', 'ee', 'jj', 'aa'],
       ['ii', 'jj', 'dd', 'gg', 'bb', 'hh'],
       ['aa', 'hh', 'bb', 'aa', 'hh', 'bb']], dtype='<U2')

In [ ]:
random.rand(4,5)

array([[0.26104029, 0.33938805, 0.29752417, 0.2415673 , 0.27554654],
       [0.3706542 , 0.63524279, 0.25098316, 0.51751413, 0.76313298],
       [0.73220043, 0.9419517 , 0.15459737, 0.08894959, 0.21994607],
       [0.52008014, 0.43017862, 0.52989846, 0.29018098, 0.12581306]])