# Support Vector Machine : Linear

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('D:/Test/D9data3.csv')
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
dataset.shape


(400, 3)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
dataset.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [6]:
# Feature column
X = dataset.iloc[:,:-1].values

#Target class
y = dataset.iloc[:,-1].values

In [7]:
#Data split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# SVM Model building : Linear

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',C=1, random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1, kernel='linear', random_state=0)

In [13]:
#Prediction
classifier.predict(sc.transform([[30, 78000]]))


array([0], dtype=int64)

In [17]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [19]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [20]:
cm=confusion_matrix(y_pred,y_test)
cm

array([[52,  3],
       [ 6, 19]], dtype=int64)

In [23]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92        55
           1       0.86      0.76      0.81        25

    accuracy                           0.89        80
   macro avg       0.88      0.85      0.86        80
weighted avg       0.89      0.89      0.89        80



In [22]:
accuracy_score(y_pred,y_test)

0.8875