In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# Assigning features and label variables
# First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']


In [8]:
#Import LabelEncoder
from sklearn.preprocessing import LabelEncoder
#Creating Labels
la = LabelEncoder()
w_encoder =la.fit_transform(weather)
w_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

sunny : 2
Rainy : 1
Overcast : 0

In [10]:
t_encoder =la.fit_transform(temp)
t_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

Cool : 0
Hot  : 1
Mild : 2

In [11]:
p_encoder =la.fit_transform(play)
p_encoder

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

Yes: 1
No : 0

In [13]:
#Combining columns
features = list(zip(w_encoder,t_encoder))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(features,p_encoder)

GaussianNB()

In [18]:
predicted = model.predict([[2,0]])
predicted

array([0], dtype=int64)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report())
# Test data needs to be provided.