# PCA

## import libs

In [ ]:
import numpy as np
import pandas as pd

## set path

In [ ]:
# from google.colab import files
# uploaded = files.upload()
# CDAC_DataBook.xlsx

import os
os.chdir(r'C:\Users\surya\Downloads')
os.getcwd()

'C:\\Users\\surya\\Downloads'

## import dataset

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='iris')

## create random sample

In [ ]:
df = df.sample(frac=1)

## X & Y

In [ ]:
x=df.drop('Species', axis=1)

In [ ]:
y=df['Species']

## Splitting

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Scaling

In [ ]:
# from sklearn.preprocessing import StandardScaler

In [ ]:
# sc = StandardScaler()

In [ ]:
# x_train = sc.fit_transform(x_train)

In [ ]:
# x_test = sc.fit(x_test)

## PCA

In [ ]:
from sklearn.decomposition import PCA

### n_components=2

In [ ]:
pca2 = PCA(n_components=2)

In [ ]:
x_train2 = pca2.fit_transform(x_train)
# fit_transform() only for training data

In [ ]:
x_test2 = pca2.transform(x_test)
# use only fit() for test data

#### explained_variance_ratio_

In [ ]:
pca2.explained_variance_ratio_
# Explained Variation of two Principal Components

array([0.92630424, 0.05258492])

In [ ]:
sum(pca2.explained_variance_ratio_)
# explains 97% variation using two Principal Components

0.9788891589656719

In [ ]:
pca2.components_
# loading of each Principal Components

array([[ 0.34718648, -0.08974167,  0.86066714,  0.36146929],
       [ 0.64094853,  0.7491188 , -0.16040358, -0.0477147 ]])

In [ ]:
pca2.components_.T
# transposes ndarray

array([[ 0.34718648,  0.64094853],
       [-0.08974167,  0.7491188 ],
       [ 0.86066714, -0.16040358],
       [ 0.36146929, -0.0477147 ]])

In [ ]:
pca2.components_.T * np.sqrt(pca2.explained_variance_ratio_)
# correlation matrix
# indicates PC1 and PC2 represented by two columns, each column representing impact of each of 4 variables
# -0.01094165 means 4th variable has least contribution to PC2
# 0.82834652 means 3rd variable has most contribution to PC1

array([[ 0.33414859,  0.14697849],
       [-0.0863716 ,  0.17178345],
       [ 0.82834652, -0.03678279],
       [ 0.34789504, -0.01094165]])

In [ ]:
df.head()

Sepal_length  Sepal_width  Petal_length  Petal_width          Species
127           6.1          3.0           4.9          1.8   Iris-virginica
78            6.0          2.9           4.5          1.5  Iris-versicolor
17            5.1          3.5           1.4          0.3      Iris-setosa
56            6.3          3.3           4.7          1.6  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor

#### RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

#### Modeling

In [ ]:
clf1 = RandomForestClassifier()

#### Training

In [ ]:
mod1 = clf1.fit(x_train, y_train)

#### Predition

In [ ]:
y_pred = mod1.predict(x_test)

#### Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

##### confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[ 6,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 10]], dtype=int64)

##### accuracy_score

In [ ]:
29/30

0.9666666666666667

In [ ]:
accuracy_score(y_test, y_pred)

0.9666666666666667

### n_components=4

In [ ]:
pca4 = PCA(n_components=4)

In [ ]:
x_train4 = pca4.fit_transform(x_train)
# fit_transform() only for training data

In [ ]:
x_test4 = pca4.transform(x_test)
# use only fit() for test data

#### explained_variance_ratio_

In [ ]:
pca4.explained_variance_ratio_
# Explained Variation of two Principal Components

array([0.92630424, 0.05258492, 0.01647984, 0.004631  ])

In [ ]:
sum(pca4.explained_variance_ratio_)
# explains 100% variation using two Principal Components

1.0

In [ ]:
pca4.components_.T
# loading of each Principal Components

array([[ 0.34718648,  0.64094853, -0.61895032, -0.29248424],
       [-0.08974167,  0.7491188 ,  0.58243251,  0.3025555 ],
       [ 0.86066714, -0.16040358,  0.0925383 ,  0.47429887],
       [ 0.36146929, -0.0477147 ,  0.51875769, -0.77327467]])

# Decision Tree
- sum of squared residuals is used to find the value of ```m``` and ```c``` in equation ```y = mx + c``` of linear regression
- sum of squared residuals should be as minimum as possible
- ```Back Propagation```
    - loss function should be minimized
    - ```Loss Function``` : sum of squared residuals
- ```Pure Split``` : when Gini Impurity is zero

# Random Forest
1. ```Bagging```
    - Decision Trees are in parallel, collective decision making with rule of majority
    - works with multiple trees in a forest
    - P(Decision Tree giving correct result), ```P(True)``` = 0.6
    - No of trees, ```n``` = 5
    - No of Trees say True, ```r``` = 3
    - Probability of ```r``` Trees saying True out of ```n``` trees = ```nCr * P(True)^r * (1-P(True))^(n-r)``` [```using Binomial Distribution```]
    - Correct Value = True
    - If three of more forest say that it is True
        - ```P(One forest will say True)``` = ```P(Three or more trees say True)```
            - ```P('r' trees say True out of 'n' Trees)``` = ```nCr * P(True)^r * (1-P(True))^(n-r)```
            - ```P(Three trees say True)``` = ```5C3 * 0.6^3 * (1-0.6)^(5-3)```
                - = ```5C3 * 0.6^3 * 0.4^2```
                - = ```0.3456```
            - ```P(Four trees say True)``` = ```5C4 * 0.6^4 * (1-0.6)^(5-4)```
                - = ```5C4 * 0.6^4 * 0.4^1```
                - = ```0.2592```
            - ```P(Five trees say True)``` = ```5C5 * 0.6^5 * (1-0.6)^(5-5)```
                - = ```5C5 * 0.6^5 * 0.4^0```
                - = ```0.07776```
            - ```P(One forest will say True)``` = ```P(Three trees say True)``` + ```P(Four trees say True)``` + ```P(Five trees say True)```
                - = ```0.3456``` + ```0.2592``` + ```0.07776```
                - = ```0.68256```
- Bootstrapping
    - another form of Bagging
    - works with multiple forests
    - No of Forests = 5
    - P(Decision Tree giving correct result), ```P(True)``` = 0.6
    - No of trees, ```n``` = 5
    - No of Trees say True, ```r``` = 3
    - Probability of ```r``` Forests saying True out of ```n``` Forests = ```nCr * P(True)^r * (1-P(True))^(n-r)``` [```using Binomial Distribution```]
    - Correct Value = True
    - If three of more forest say that it is True
        - ```P(One forest will say True)``` = ```P(Three or more trees say True)```
            - ```P('r' trees say True out of 'n' Trees)``` = ```nCr * P(True)^r * (1-P(True))^(n-r)```
            - ```P(Three Forests say True)``` = ```5C3 * 0.6^3 * (1-0.6)^(5-3)```
                - = ```5C3 * 0.6^3 * 0.4^2```
                - = ```0.320439```
            - ```P(Four Forests say True)``` = ```5C4 * 0.6^4 * (1-0.6)^(5-4)```
                - = ```5C4 * 0.6^4 * 0.4^1```
                - = ```0.148151```
            - ```P(Five Forests say True)``` = ```5C5 * 0.6^5 * (1-0.6)^(5-5)```
                - = ```5C5 * 0.6^5 * 0.4^0```
                - = ```0.07776```
            - ```P(One set of Forests will say True)``` = ```P(Three Forests say True)``` + ```P(Four Forests say True)``` + ```P(Five Forests say True)```
                - = ```0.320439``` + ```0.344505``` + ```0.148151```
                - = ```0.813095```
        - Note that, in aggregation probability of correct prediction has increased
2. ```Boosting```
    - Decision Trees are put in series and keep on boosting
    - helps weak learners to become strong learners by making weak learners learn again in the series, so last learner is a strong learner
    - weights (```α1```, ```α2```, ```α3```, ```...```) are assigned to each learner, and weights are adjusted after each learner to reduce error
    - keeps on aggregating repetitively
    
    - Two types of boosting
        1. ```Gradient Boosting / Descent```
            - Hyper Parameters
                - Alpha, ```α``` : Learning Rate / Speed of convergance /  [between ```0 and 1```]
            - Steps
            1. Create a base model, Average of all values
            2. Calculate the residuals based on predicted value from base model
            3. Create Decision Tree (DT1) with the inputs as Experience, Education and output as Residuals(D)
            4. Generate Predictions for DT1
            5. Calculate resuduals (resid2) based on predicted values of DT1
            6. ```New Prediction``` = ```Previous prediction``` + ```Prediction from tree based on residuals(NewPred1A)```
            7. To avoid overfitting the previous equation of Row#1 is changed to
                - ```New Prediction``` = ```Previous Prediction``` + ```Learning Rate, α``` * ```Prediction from tree based on Residuals```
                - Learning Rate, ```α``` will always be between ```0 and 1```, preferable around ```0.1 to 0.15```
                - Low value of Learning rate makes take small steps, so it takes more time
                - High value of Learning rate make take big steps, so it takes less time
        2. ```XG Boosting``` / ```eXtreme Gradient Boosting```
            - Hyperparameters / Terminology
                - Lambda, ```λ``` : L2 Regularization Parameter
                    - analogous to Ridge regression
                    - can control Gain to reduce the Similarity Score to ultimately reduce the Gain below Pruning threshold(```γ```)
                    - decides how many split can be made
                    - if ```λ``` = 0, outliers have more effect, so to reduce effect of outliers or even errors, we introduce Regularization parameter ```λ```
                    - with introduction of regularization parameter ```λ```, we can reduce the impact of outliers
                - Eta, ```η``` : Learning Rate / Speed of convergance
                    - between ```0 and 1```
                    - Analogous to the learning rate in GBM
                - Gamma, ```γ``` : Threshold of Pruning
                - ```Similarity Score 1``` = ```Square(sum(residuals))/(No of values)```
                    - = ```(∑ Residuals)^2``` / ```No of values```
                - ```Similarity Score 2``` = ```Square(sum(residuals))/(No of values + Regularization Parameter) ```
                    - = ```(∑ Residuals)^2``` / ```(No of values + λ)```
            - Steps
                1. Create a base model to make the first prediction
                2. we consider the first prediction
                3. we decide the criteria as Exp>=5
                    - Row # 2, 4 go on one side, Row # 3, 5, 6 go on the other side
                4.


In [ ]:
RandomForestClassifier()

## GradientBoostingClassifier

### Set path

In [ ]:
# from google.colab import files
# uploaded = files.upload()
# CDAC_DataBook.xlsx

import os
os.chdir(r'C:\Users\surya\Downloads')
os.getcwd()

'C:\\Users\\surya\\Downloads'

### load dataset

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='diabetes')

### X & Y

In [ ]:
x = df.drop('Outcome', axis=1)

In [ ]:
y = df['Outcome']

### splitting

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

### Modeling

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gbc = GradientBoostingClassifier(learning_rate=0.1)

### Training

In [ ]:
mod1 = gbc.fit(x_train, y_train)

### Prediction

In [ ]:
y_pred = mod1.predict(x_test)

### Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

##### confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[94, 13],
       [14, 33]], dtype=int64)

##### accuracy_score

In [ ]:
accuracy_score(y_test, y_pred)

0.8246753246753247