# Support Vector Machine : Kernel

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('D:/Test/D9data3.csv')
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
dataset.shape

(400, 3)

In [4]:
# Feature column
X = dataset.iloc[:,:-1].values

#Target class
y = dataset.iloc[:,-1].values

In [5]:
#Data split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# SVM Model buildig : Kernel Function

In [7]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',C=1,random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1, random_state=0)

In [8]:
classifier.predict(sc.transform([[24,45000]]))

array([0], dtype=int64)

In [11]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_pred,y_test)
cm

array([[54,  1],
       [ 4, 21]], dtype=int64)

In [13]:
accuracy_score(y_pred,y_test)

0.9375